steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Image
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/github.com/exauceh/gcpu_hackathon:$COMMIT_SHA'
    - '.'

# Spécifiez le bucket des logs ici
logsBucket: 'gs://VOTRE_NOM_DE_BUCKET'

images:
- 'gcr.io/$PROJECT_ID/github.com/exauceh/gcpu_hackathon:$COMMIT_SHA'

# Raccordez votre build au compte de service que vous avez spécifié
# dans le déclencheur (gcpu-hackathon@...)
options:
  serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/gcpu-hackathon@gcpu-hackathon-2025-474123.iam.gserviceaccount.com'