steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Image
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/github.com/exauceh/gcpu_hackathon:$COMMIT_SHA'
    - '.'

# ÉTAPE AJOUTÉE : Déploiement sur Cloud Run
- name: - name: 'us-central1-docker.pkg.dev/cloud-sdk/cloud-sdk/gcloud' # <-- NOUVEAU CHEMIN

  args:
    - gcloud
    - run
    - deploy
    - gcpu-hackathon-2025 # <--- REMPLACEZ PAR LE NOM DU SERVICE
    - --image
    - 'gcr.io/$PROJECT_ID/github.com/exauceh/gcpu_hackathon:$COMMIT_SHA'
    - --region
    - europe-west9 # <--- Vérifiez votre région (Paris)
    - --platform
    - managed



# Spécifiez le bucket des logs ici
logsBucket: 'gs://gcpu-hackathon-logs-474123' # Utilisez le nom de votre bucket créé

images:
- 'gcr.io/$PROJECT_ID/github.com/exauceh/gcpu_hackathon:$COMMIT_SHA'

# La section 'options' est désormais vide ou supprimée
# puisque le compte de service est défini par le déclencheur.